import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const read = path => readFileSync(resolve(root, path), 'utf8');

test('cloud deployment files are safe and complete', () => {
  const migration = read('database/migrations/001_initial_schema.sql');
  const intelligenceMigration = read('database/migrations/002_product_intelligence.sql');
  const factoryMigration = read('database/migrations/003_ai_product_content_factory.sql');
  const imageMigration = read('database/migrations/004_real_ai_image_generation.sql');
  const opportunityMigration = read('database/migrations/005_opportunity_intelligence_engine.sql');
  const costMigration = read('database/migrations/006_ai_cost_control.sql');
  const salesMigration = read('database/migrations/007_sales_intelligence_part1.sql');
  const quoteMigration = read('database/migrations/008_quote_pi_builder.sql');
  const customQuoteMigration = read('database/migrations/009_custom_quote_items.sql');
  const globalPiMigration = read('database/migrations/010_global_pi_template.sql');
  const professionalPiMigration = read('database/migrations/011_professional_pi_optimization.sql');
  const productFoundationMigration = read('database/migrations/012_product_foundation.sql');
  const productMasterDataMigration = read('database/migrations/013_product_master_data.sql');
  const pimFoundationMigration = read('database/migrations/014_pim_foundation_upgrade.sql');
  const aiProductImportMigration = read('database/migrations/015_ai_product_import.sql');
  const render = read('render.yaml');
  const env = read('.env.example');
  const ignore = read('.gitignore');
  const packageJson = JSON.parse(read('package.json'));

  assert.doesNotMatch(migration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(migration, /CREATE TABLE IF NOT EXISTS products/);
  assert.match(migration, /ON CONFLICT \(version\) DO NOTHING/);
  assert.doesNotMatch(intelligenceMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(intelligenceMigration, /ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title/);
  assert.match(intelligenceMigration, /CREATE TABLE IF NOT EXISTS product_related_category_links/);
  assert.match(intelligenceMigration, /'002_product_intelligence'/);
  assert.doesNotMatch(factoryMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(factoryMigration, /CREATE TABLE IF NOT EXISTS ai_product_content_drafts/);
  assert.match(factoryMigration, /CREATE TABLE IF NOT EXISTS ai_image_generation_tasks/);
  assert.match(factoryMigration, /'003_ai_product_content_factory'/);
  assert.doesNotMatch(imageMigration, /\b(DROP TABLE|DROP COLUMN|TRUNCATE)\b/i);
  assert.match(imageMigration, /ADD COLUMN IF NOT EXISTS lifecycle_status/);
  assert.match(imageMigration, /ADD COLUMN IF NOT EXISTS provider_request_id/);
  assert.match(imageMigration, /'004_real_ai_image_generation'/);
  assert.doesNotMatch(opportunityMigration, /\b(DROP TABLE|DROP COLUMN|TRUNCATE)\b/i);
  assert.match(opportunityMigration, /CREATE TABLE IF NOT EXISTS customers/);
  assert.match(opportunityMigration, /CREATE TABLE IF NOT EXISTS customer_product_recommendations/);
  assert.match(opportunityMigration, /CREATE TABLE IF NOT EXISTS customer_outreach_drafts/);
  assert.match(opportunityMigration, /'005_opportunity_intelligence_engine'/);
  assert.match(costMigration, /'006_ai_cost_control'/);
  assert.match(costMigration, /CREATE TABLE IF NOT EXISTS ai_cost_settings/);
  assert.match(costMigration, /CREATE TABLE IF NOT EXISTS ai_cost_logs/);
  assert.match(costMigration, /CREATE TABLE IF NOT EXISTS ai_cache_records/);
  assert.doesNotMatch(costMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(salesMigration, /'007_sales_intelligence_part1'/);
  assert.match(salesMigration, /CREATE TABLE IF NOT EXISTS sales_inquiries/);
  assert.match(salesMigration, /CREATE TABLE IF NOT EXISTS sales_quotes/);
  assert.match(salesMigration, /CREATE TABLE IF NOT EXISTS sales_orders/);
  assert.doesNotMatch(salesMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(quoteMigration, /'008_quote_pi_builder'/);
  assert.match(quoteMigration, /CREATE TABLE IF NOT EXISTS sales_quote_versions/);
  assert.match(quoteMigration, /CREATE TABLE IF NOT EXISTS sales_order_items/);
  assert.doesNotMatch(quoteMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(customQuoteMigration, /'009_custom_quote_items'/);
  assert.match(customQuoteMigration, /CREATE TABLE IF NOT EXISTS sales_quote_custom_items/);
  assert.match(customQuoteMigration, /CREATE TABLE IF NOT EXISTS sales_order_custom_items/);
  assert.doesNotMatch(customQuoteMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(globalPiMigration, /'010_global_pi_template'/);
  assert.match(globalPiMigration, /CREATE TABLE IF NOT EXISTS organization_bank_accounts/);
  assert.match(globalPiMigration, /ALTER TABLE sales_quotes ADD COLUMN IF NOT EXISTS project_name/);
  assert.match(professionalPiMigration, /'011_professional_pi_optimization'/);
  assert.match(professionalPiMigration, /confirmed_material/);
  assert.match(professionalPiMigration, /total_cbm_override/);
  assert.doesNotMatch(professionalPiMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(productFoundationMigration, /'012_product_foundation'/);
  assert.match(productFoundationMigration, /CREATE TABLE IF NOT EXISTS product_variants/);
  assert.match(productFoundationMigration, /CREATE TABLE IF NOT EXISTS product_attribute_definitions/);
  assert.doesNotMatch(productFoundationMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(productMasterDataMigration, /'013_product_master_data'/);
  assert.match(productMasterDataMigration, /CREATE TABLE IF NOT EXISTS product_attribute_category_links/);
  assert.match(productMasterDataMigration, /CREATE TABLE IF NOT EXISTS product_attribute_options/);
  assert.doesNotMatch(productMasterDataMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(pimFoundationMigration, /'014_pim_foundation_upgrade'/);
  assert.match(pimFoundationMigration, /ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS cbm/);
  assert.match(pimFoundationMigration, /ALTER TABLE sales_quote_items ADD COLUMN IF NOT EXISTS product_snapshot/);
  assert.doesNotMatch(pimFoundationMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(aiProductImportMigration, /'015_ai_product_import'/);
  assert.match(aiProductImportMigration, /CREATE TABLE IF NOT EXISTS product_import_batches/);
  assert.match(aiProductImportMigration, /CREATE TABLE IF NOT EXISTS product_import_drafts/);
  assert.doesNotMatch(aiProductImportMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.doesNotMatch(globalPiMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(render, /buildCommand: npm install/);
  assert.match(render, /startCommand: npm start/);
  assert.match(render, /healthCheckPath: \/api\/health/);
  assert.match(render, /key: DATABASE_URL\s+sync: false/);
  assert.match(env, /DATABASE_URL=/);
  assert.match(ignore, /^\.env\.local$/m);
  assert.equal(packageJson.dependencies.pg.startsWith('^8.'), true);
  assert.equal(packageJson.scripts.start, 'node src/server.mjs');
});

test('health check validates the database and returns the required payload', () => {
  const server = read('src/server.mjs');
  assert.match(server, /db\.prepare\('SELECT 1 AS ok'\)\.get\(\)/);
  assert.match(server, /json\(res, 200, \{ status: 'ok' \}\)/);
  assert.match(server, /const PORT = process\.env\.PORT \|\| 3000/);
  assert.match(server, /server\.listen\(PORT, "0\.0\.0\.0"/);
  assert.match(server, /Server listening on 0\.0\.0\.0:\$\{PORT\}/);
  assert.ok(server.indexOf('server.listen(PORT, "0.0.0.0"') < server.indexOf('setTimeout(initializeDatabase, databaseInitializationDelayMs)'));
  assert.match(server, /url\.pathname === '\/api\/ready'/);
  assert.match(server, /url\.pathname === '\/api\/debug\/db'/);
  assert.match(server, /SELECT version FROM schema_migrations WHERE version = \?/);
  assert.match(server, /information_schema\.tables/);
});
