import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const read = path => readFileSync(resolve(root, path), 'utf8');

test('cloud deployment files are safe and complete', () => {
  const migration = read('database/migrations/001_initial_schema.sql');
  const intelligenceMigration = read('database/migrations/002_product_intelligence.sql');
  const factoryMigration = read('database/migrations/003_ai_product_content_factory.sql');
  const imageMigration = read('database/migrations/004_real_ai_image_generation.sql');
  const opportunityMigration = read('database/migrations/005_opportunity_intelligence_engine.sql');
  const costMigration = read('database/migrations/006_ai_cost_control.sql');
  const salesMigration = read('database/migrations/007_sales_intelligence_part1.sql');
  const quoteMigration = read('database/migrations/008_quote_pi_builder.sql');
  const customQuoteMigration = read('database/migrations/009_custom_quote_items.sql');
  const globalPiMigration = read('database/migrations/010_global_pi_template.sql');
  const professionalPiMigration = read('database/migrations/011_professional_pi_optimization.sql');
  const productFoundationMigration = read('database/migrations/012_product_foundation.sql');
  const productMasterDataMigration = read('database/migrations/013_product_master_data.sql');
  const pimFoundationMigration = read('database/migrations/014_pim_foundation_upgrade.sql');
  const aiProductImportMigration = read('database/migrations/015_ai_product_import.sql');
  const businessReadinessMigration = read('database/migrations/016_product_library_business_readiness.sql');
  const priceEngineMigration = read('database/migrations/017_product_price_engine.sql');
  const aiBusinessBrainMigration = read('database/migrations/018_v53_ai_business_brain_foundation.sql');
  const customerIntelligenceMigration = read('database/migrations/019_v53_phase2a_customer_intelligence_mvp.sql');
  const discoveryAssistantMigration = read('database/migrations/020_v53_opportunity_discovery_assistant.sql');
  const searchTaskMigration = read('database/migrations/021_v53_search_task_execution_center.sql');
  const customerIntelligenceUpdateMigration = read('database/migrations/022_v53_customer_intelligence_update_history.sql');
  const searchResultStorageMigration = read('database/migrations/023_v53_search_result_storage.sql');
  const customerSourceMigration = read('database/migrations/024_v53_customer_source.sql');
  const knowledgeCenterMigration = read('database/migrations/025_v53_ai_knowledge_center_foundation.sql');
  const searchStrategyMigration = read('database/migrations/026_v53_search_strategy_human_approval.sql');
  const terminalPhaseMigration = read('database/migrations/028_search_execution_terminal_phase.sql');
  const productCorrectionMigration = read('database/migrations/029_product_foundation_correction.sql');
  const render = read('render.yaml');
  const env = read('.env.example');
  const ignore = read('.gitignore');
  const packageJson = JSON.parse(read('package.json'));
  const indexHtml = read('public/index.html');
  const app = read('public/app.js');
  const server = read('src/server.mjs');

  assert.doesNotMatch(migration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(migration, /CREATE TABLE IF NOT EXISTS products/);
  assert.match(migration, /ON CONFLICT \(version\) DO NOTHING/);
  assert.doesNotMatch(intelligenceMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(intelligenceMigration, /ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title/);
  assert.match(intelligenceMigration, /CREATE TABLE IF NOT EXISTS product_related_category_links/);
  assert.match(intelligenceMigration, /'002_product_intelligence'/);
  assert.doesNotMatch(factoryMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(factoryMigration, /CREATE TABLE IF NOT EXISTS ai_product_content_drafts/);
  assert.match(factoryMigration, /CREATE TABLE IF NOT EXISTS ai_image_generation_tasks/);
  assert.match(factoryMigration, /'003_ai_product_content_factory'/);
  assert.doesNotMatch(imageMigration, /\b(DROP TABLE|DROP COLUMN|TRUNCATE)\b/i);
  assert.match(imageMigration, /ADD COLUMN IF NOT EXISTS lifecycle_status/);
  assert.match(imageMigration, /ADD COLUMN IF NOT EXISTS provider_request_id/);
  assert.match(imageMigration, /'004_real_ai_image_generation'/);
  assert.doesNotMatch(opportunityMigration, /\b(DROP TABLE|DROP COLUMN|TRUNCATE)\b/i);
  assert.match(opportunityMigration, /CREATE TABLE IF NOT EXISTS customers/);
  assert.match(opportunityMigration, /CREATE TABLE IF NOT EXISTS customer_product_recommendations/);
  assert.match(opportunityMigration, /CREATE TABLE IF NOT EXISTS customer_outreach_drafts/);
  assert.match(opportunityMigration, /'005_opportunity_intelligence_engine'/);
  assert.match(costMigration, /'006_ai_cost_control'/);
  assert.match(costMigration, /CREATE TABLE IF NOT EXISTS ai_cost_settings/);
  assert.match(costMigration, /CREATE TABLE IF NOT EXISTS ai_cost_logs/);
  assert.match(costMigration, /CREATE TABLE IF NOT EXISTS ai_cache_records/);
  assert.doesNotMatch(costMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(salesMigration, /'007_sales_intelligence_part1'/);
  assert.match(salesMigration, /CREATE TABLE IF NOT EXISTS sales_inquiries/);
  assert.match(salesMigration, /CREATE TABLE IF NOT EXISTS sales_quotes/);
  assert.match(salesMigration, /CREATE TABLE IF NOT EXISTS sales_orders/);
  assert.doesNotMatch(salesMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(quoteMigration, /'008_quote_pi_builder'/);
  assert.match(quoteMigration, /CREATE TABLE IF NOT EXISTS sales_quote_versions/);
  assert.match(quoteMigration, /CREATE TABLE IF NOT EXISTS sales_order_items/);
  assert.doesNotMatch(quoteMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(customQuoteMigration, /'009_custom_quote_items'/);
  assert.match(customQuoteMigration, /CREATE TABLE IF NOT EXISTS sales_quote_custom_items/);
  assert.match(customQuoteMigration, /CREATE TABLE IF NOT EXISTS sales_order_custom_items/);
  assert.doesNotMatch(customQuoteMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(globalPiMigration, /'010_global_pi_template'/);
  assert.match(globalPiMigration, /CREATE TABLE IF NOT EXISTS organization_bank_accounts/);
  assert.match(globalPiMigration, /ALTER TABLE sales_quotes ADD COLUMN IF NOT EXISTS project_name/);
  assert.match(professionalPiMigration, /'011_professional_pi_optimization'/);
  assert.match(professionalPiMigration, /confirmed_material/);
  assert.match(professionalPiMigration, /total_cbm_override/);
  assert.doesNotMatch(professionalPiMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(productFoundationMigration, /'012_product_foundation'/);
  assert.match(productFoundationMigration, /CREATE TABLE IF NOT EXISTS product_variants/);
  assert.match(productFoundationMigration, /CREATE TABLE IF NOT EXISTS product_attribute_definitions/);
  assert.doesNotMatch(productFoundationMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(productMasterDataMigration, /'013_product_master_data'/);
  assert.match(productMasterDataMigration, /CREATE TABLE IF NOT EXISTS product_attribute_category_links/);
  assert.match(productMasterDataMigration, /CREATE TABLE IF NOT EXISTS product_attribute_options/);
  assert.match(productCorrectionMigration, /CREATE TABLE IF NOT EXISTS product_variant_axes/);
  assert.match(productCorrectionMigration, /CREATE TABLE IF NOT EXISTS product_variant_option_values/);
  assert.match(productCorrectionMigration, /can_be_variant_axis/);
  assert.doesNotMatch(productMasterDataMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(pimFoundationMigration, /'014_pim_foundation_upgrade'/);
  assert.match(pimFoundationMigration, /ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS cbm/);
  assert.match(pimFoundationMigration, /ALTER TABLE sales_quote_items ADD COLUMN IF NOT EXISTS product_snapshot/);
  assert.doesNotMatch(pimFoundationMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(aiProductImportMigration, /'015_ai_product_import'/);
  assert.match(aiProductImportMigration, /CREATE TABLE IF NOT EXISTS product_import_batches/);
  assert.match(aiProductImportMigration, /CREATE TABLE IF NOT EXISTS product_import_drafts/);
  assert.doesNotMatch(aiProductImportMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(businessReadinessMigration, /'016_product_library_business_readiness'/);
  assert.match(businessReadinessMigration, /ALTER TABLE products ADD COLUMN IF NOT EXISTS source_supplier/);
  assert.doesNotMatch(businessReadinessMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(priceEngineMigration, /'017_product_price_engine'/);
  assert.match(priceEngineMigration, /CREATE TABLE IF NOT EXISTS product_price_rules/);
  assert.match(priceEngineMigration, /reference_price_snapshot/);
  assert.match(priceEngineMigration, /cost_snapshot/);
  assert.doesNotMatch(priceEngineMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(aiBusinessBrainMigration, /'018_v53_ai_business_brain_foundation'/);
  assert.match(aiBusinessBrainMigration, /CREATE TABLE IF NOT EXISTS ai_prompt_templates/);
  assert.match(aiBusinessBrainMigration, /CREATE TABLE IF NOT EXISTS ai_context_snapshots/);
  assert.match(aiBusinessBrainMigration, /CREATE TABLE IF NOT EXISTS ai_execution_logs/);
  assert.doesNotMatch(aiBusinessBrainMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(customerIntelligenceMigration, /'019_v53_phase2a_customer_intelligence_mvp'/);
  assert.match(customerIntelligenceMigration, /CREATE TABLE IF NOT EXISTS customer_intelligence_profiles/);
  assert.match(customerIntelligenceMigration, /CREATE TABLE IF NOT EXISTS customer_intelligence_feedback/);
  assert.match(customerIntelligenceMigration, /CREATE TABLE IF NOT EXISTS customer_score_history/);
  assert.doesNotMatch(customerIntelligenceMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(discoveryAssistantMigration, /'020_v53_opportunity_discovery_assistant'/);
  assert.match(discoveryAssistantMigration, /CREATE TABLE IF NOT EXISTS customer_type_profiles/);
  assert.match(discoveryAssistantMigration, /CREATE TABLE IF NOT EXISTS customer_type_score_dimensions/);
  assert.match(discoveryAssistantMigration, /CREATE TABLE IF NOT EXISTS customer_discovery_requests/);
  assert.doesNotMatch(discoveryAssistantMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(searchTaskMigration, /'021_v53_search_task_execution_center'/);
  assert.match(searchTaskMigration, /CREATE TABLE IF NOT EXISTS search_tasks/);
  assert.match(searchTaskMigration, /REFERENCES customer_discovery_requests\(id\) ON DELETE SET NULL/);
  assert.doesNotMatch(searchTaskMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(customerIntelligenceUpdateMigration, /'022_v53_customer_intelligence_update_history'/);
  assert.match(customerIntelligenceUpdateMigration, /CREATE TABLE IF NOT EXISTS customer_intelligence_updates/);
  assert.match(customerIntelligenceUpdateMigration, /ON CONFLICT \(version\) DO NOTHING/);
  assert.doesNotMatch(customerIntelligenceUpdateMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(searchResultStorageMigration, /'023_v53_search_result_storage'/);
  assert.match(searchResultStorageMigration, /CREATE TABLE IF NOT EXISTS search_results/);
  assert.match(searchResultStorageMigration, /REFERENCES search_tasks\(id\) ON DELETE CASCADE/);
  assert.match(searchResultStorageMigration, /ON CONFLICT \(version\) DO NOTHING/);
  assert.doesNotMatch(searchResultStorageMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(customerSourceMigration, /'024_v53_customer_source'/);
  assert.match(customerSourceMigration, /ADD COLUMN IF NOT EXISTS customer_source/);
  assert.match(customerSourceMigration, /ADD COLUMN IF NOT EXISTS is_test_data/);
  assert.match(customerSourceMigration, /ADD COLUMN IF NOT EXISTS recommended_product_reason/);
  assert.match(customerSourceMigration, /WHEN 'Google Maps' THEN 'Google Maps'/);
  assert.match(customerSourceMigration, /WHEN 'Website' THEN 'Website'/);
  assert.match(customerSourceMigration, /WHEN 'Instagram' THEN 'Instagram'/);
  assert.match(customerSourceMigration, /WHEN 'Facebook' THEN 'Facebook'/);
  assert.match(customerSourceMigration, /google_maps_url/);
  assert.match(customerSourceMigration, /google\.com\/maps|google%maps/);
  assert.doesNotMatch(customerSourceMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(knowledgeCenterMigration, /'025_v53_ai_knowledge_center_foundation'/);
  assert.match(knowledgeCenterMigration, /CREATE TABLE IF NOT EXISTS knowledge_items/);
  assert.match(knowledgeCenterMigration, /knowledge_type IN \('company', 'target_customer_profile'\)/);
  assert.match(knowledgeCenterMigration, /status IN \('Draft', 'Active', 'Needs Review', 'Outdated', 'Archived'\)/);
  assert.match(knowledgeCenterMigration, /UNIQUE \(knowledge_key, revision_no\)/);
  assert.match(knowledgeCenterMigration, /WHERE status = 'Active'/);
  assert.doesNotMatch(knowledgeCenterMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(searchStrategyMigration, /'026_v53_search_strategy_human_approval'/);
  assert.match(searchStrategyMigration, /CREATE TABLE IF NOT EXISTS search_strategies/);
  assert.match(searchStrategyMigration, /UNIQUE\(strategy_key, revision_no\)/);
  assert.match(searchStrategyMigration, /WHERE status='Approved'/);
  assert.doesNotMatch(searchStrategyMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.doesNotMatch(globalPiMigration, /\b(DROP|TRUNCATE)\b/i);
  assert.match(render, /buildCommand: npm install/);
  assert.match(render, /startCommand: npm start/);
  assert.match(render, /healthCheckPath: \/api\/health/);
  assert.match(render, /key: DATABASE_URL\s+sync: false/);
  assert.match(env, /DATABASE_URL=/);
  assert.match(ignore, /^\.env\.local$/m);
  assert.equal(packageJson.dependencies.pg.startsWith('^8.'), true);
  assert.equal(packageJson.scripts.start, 'node src/server.mjs');
  assert.match(indexHtml, /\/app\.js\?v=__BUILD_VERSION__/);
  assert.match(indexHtml, /\/styles\.css\?v=__BUILD_VERSION__/);
  assert.match(server, /no-cache, no-store, must-revalidate/);
  assert.match(server, /replaceAll\('__BUILD_VERSION__', buildVersion\)/);
  assert.match(app, /route: 'knowledge-dashboard'/);
  assert.match(app, /'knowledge-dashboard': renderKnowledgeDashboard/);
  assert.match(app, /navigationItemsForRole\(uniqueNavItems, state\.user\.role/);
  assert.match(app, /Company Knowledge/);
  assert.match(app, /Target Customer Profiles/);
  assert.match(app, /Save Draft/);
  assert.match(app, /Search Strategies/);
  assert.match(app, /Create Strategy Draft/);
  assert.match(app, /data-action="strategy-archive"/);
  assert.match(app, /Archive Search Strategy\?/);
  assert.match(app, /will not delete the record/);
  assert.match(app, /button--risk/);
  assert.match(app, /Unavailable while Search Task/);
  assert.match(app, /Archived \(\$\{archivedCount\}\)/);
  assert.match(app, /strategyKeywordTags/);
  assert.match(server, /026_v53_search_strategy_human_approval/);
  assert.match(terminalPhaseMigration, /'Complete','Partial Complete'/);
  assert.match(server, /028_search_execution_terminal_phase/);
  assert.match(server, /029_product_foundation_correction/);
});

test('health check validates the database and returns the required payload', () => {
  const server = read('src/server.mjs');
  assert.match(server, /db\.prepare\('SELECT 1 AS ok'\)\.get\(\)/);
  assert.match(server, /json\(res, 200, \{ status: 'ok' \}\)/);
  assert.match(server, /const PORT = process\.env\.PORT \|\| 3000/);
  assert.match(server, /server\.listen\(PORT, "0\.0\.0\.0"/);
  assert.match(server, /Server listening on 0\.0\.0\.0:\$\{PORT\}/);
  assert.ok(server.indexOf('server.listen(PORT, "0.0.0.0"') < server.indexOf('setTimeout(initializeDatabase, databaseInitializationDelayMs)'));
  assert.match(server, /url\.pathname === '\/api\/ready'/);
  assert.match(server, /url\.pathname === '\/api\/debug\/db'/);
  assert.match(server, /SELECT version FROM schema_migrations WHERE version = \?/);
  assert.match(server, /information_schema\.tables/);
});
